name: testdevopsch

on: 
  push:
    branches:
      - 'develop'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: use nodejs v15.14.0
        uses: action/setup-node@v2
        with:
          node-version: '15.14.0'

      - name: install dependencies
        run: npm install

      - name: Linter(ESLint)
        run: npm run lint

      - name: Formatter (Prettier)
        run: npm run prettier

      - name: Test (Jest)
        env: 
          CI: true
        run: npm run build
